script: "bundle exec rake db:drop db:create db:migrate spec"

before_script:
  - "cp config/database.example.yml config/database.yml"
  - "cp config/private.example.yml config/private.yml"

rvm:
  - 1.9.2
